language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - psql -c "CREATE USER andy WITH PASSWORD 'postgres';" -U postgres
  - psql -c "CREATE DATABASE MyDiaryTestDB;" -U postgres
  - npm i -D coveralls 
script:
  - npm run db-test
after_success:
  - npm run coverage
  - npm run report-coverage
env:
  global:
    - TEST_DATABASE=MyDiaryTestDB
    - DB_PASSWORD=postgres
    - jwtKEY='amazing_grace'
    -DB_USER='andy'
